/**
 * Link Preview Utilities
 *
 * Helper functions for accessing cached LinkPreview data and generating
 * Cloudflare-transformed image URLs.
 */

import { getCFImageUrl, type CFImageOptions } from './cloudflare-images';
import { CF_IMAGE_PRESETS } from '../consts';

// Import the cache manifest - will be generated by the prebuild script
import linkPreviewCache from '../data/link-preview-cache.json';

export interface LinkPreviewCacheEntry {
  localImage: string | null;
  originalImage: string | null;
  title: string;
  description: string;
  imageAlt?: string;
  fetchedAt: string;
}

type LinkPreviewCacheType = Record<string, LinkPreviewCacheEntry>;

/**
 * Get the cached data for a LinkPreview URL
 */
export function getLinkPreviewData(url: string): LinkPreviewCacheEntry | null {
  return (linkPreviewCache as LinkPreviewCacheType)[url] || null;
}

/**
 * Check if a URL has a locally cached image
 */
export function hasLocalImage(url: string): boolean {
  const entry = getLinkPreviewData(url);
  return Boolean(entry?.localImage);
}

/**
 * Get the image URL for a LinkPreview, with optional Cloudflare transformations
 *
 * Returns the local image with CF transformations if available,
 * otherwise falls back to the original external URL.
 */
export function getLinkPreviewImage(
  url: string,
  options?: CFImageOptions
): string | null {
  const entry = getLinkPreviewData(url);

  if (!entry) return null;

  if (entry.localImage) {
    // Apply Cloudflare transformations to local image
    return getCFImageUrl(entry.localImage, options || {
      width: 1200,
      quality: CF_IMAGE_PRESETS.linkPreview.quality,
      format: CF_IMAGE_PRESETS.linkPreview.format,
    });
  }

  // Fall back to original external URL (no transformations)
  return entry.originalImage;
}

/**
 * Get responsive srcset for a LinkPreview image
 */
export function getLinkPreviewSrcSet(url: string): string | null {
  const entry = getLinkPreviewData(url);

  if (!entry?.localImage) return null;

  const widths = CF_IMAGE_PRESETS.linkPreview.widths;
  const quality = CF_IMAGE_PRESETS.linkPreview.quality;
  const format = CF_IMAGE_PRESETS.linkPreview.format;

  return widths
    .map(w => `${getCFImageUrl(entry.localImage!, { width: w, quality, format })} ${w}w`)
    .join(', ');
}

/**
 * Get all cached URLs
 */
export function getAllCachedUrls(): string[] {
  return Object.keys(linkPreviewCache as LinkPreviewCacheType);
}
