name = 'PaperMod RussCloud Overide'
license = 'MIT'
licenselink = 'https://github.com/owner/repo/LICENSE'
description = 'My overrides for the PaperMod theme'

# The home page of the theme, where the source can be found
homepage = 'http://github.com/russmckendrick/blog'

# If you have a running demo of the theme
demosite = 'https://www.russ.cloud/'

# Taxonomy terms
tags = ['blog']
features = ['papermod', 'overide']

# If the theme has multiple authors
authors = [
  {name = 'Russ Mckendrick', homepage = 'https://www.russ.cloud/'},
]

# If the theme has a single author
[author]
  name = 'Russ McKendrick'
  homepage = 'https://www.russ.cloud/'

# If porting an existing theme
[original]
  author = 'Aditya Telange'
  homepage = 'https://adityatelange.in/'
  repo = 'https://github.com/adityatelange/'
